### ISSUE TITLE
Bug反馈: [ 无法滑开屏幕解锁]

### ISSUE THREAD

**Issue by CleverPuppy** [SuperMonster003/Ant-Forest#444]
**问题描述**
脚本无法滑开屏幕进入到输入密码的页面

**日志截图**

```
2021-03-16/08:54:29.779/V: 开始运行[/storage/emulated/0/脚本/AntForest/ant-forest-launcher.js]
2021-03-16/08:54:30.508/D: ---------------------------------
2021-03-16/08:54:30.510/V: >> - - - - - - - - - - - - - - - - - -
2021-03-16/08:54:30.511/V: >> 开发者测试日志已启用
2021-03-16/08:54:30.511/V: >> - - - - - - - - - - - - - - - - - -
2021-03-16/08:54:30.512/V: >> 设备型号: realme RMX1971
2021-03-16/08:54:30.515/V: >> 屏幕宽高: 1080 × 2340
2021-03-16/08:54:30.516/V: >> 可用屏幕高度: 2264
2021-03-16/08:54:30.527/V: >> Auto.js版本: 4.1.1 Alpha2
2021-03-16/08:54:30.528/V: >> 项目版本: v2.0.4
2021-03-16/08:54:30.529/V: >> 安卓SDK版本: 29
2021-03-16/08:54:30.529/V: >> 安卓系统版本: 10
2021-03-16/08:54:30.530/V: >> Root权限: 无效
2021-03-16/08:54:30.532/V: >> 前置应用黑名单检测通过:
2021-03-16/08:54:30.533/V: >> com.android.systemui
2021-03-16/08:54:30.534/V: >> 定时循环功能未开启
2021-03-16/08:54:30.536/V: >> 设置音量键监听器
2021-03-16/08:54:30.537/V: >> "通话状态"事件监测已开启
2021-03-16/08:54:30.539/V: >> "屏幕关闭"事件监测已开启
2021-03-16/08:54:30.541/V: >> 已开启账户登出监测线程
2021-03-16/08:54:30.968/E: Error: Can not parse num param for cTrans() (file:/storage/emulated/0/脚本/AntForest/modules/mod-unlock.js#302)
Error: Can not parse num param for cTrans()
    at _cTrans (file:/storage/emulated/0/脚本/AntForest/modules/mod-unlock.js:302:0)
    at file:/storage/emulated/0/脚本/AntForest/modules/mod-unlock.js:1132:0
    at _dismiss (file:/storage/emulated/0/脚本/AntForest/modules/mod-unlock.js:1132:0)
    at file:/storage/emulated/0/脚本/AntForest/modules/mod-unlock.js:1112:0
    at _unlock (file:/storage/emulated/0/脚本/AntForest/modules/mod-unlock.js:2056:0)
    at /storage/emulated/0/脚本/AntForest/ant-forest-launcher.js:3853:0
    at /storage/emulated/0/脚本/AntForest/ant-forest-launcher.js:6769:0

2021-03-16/08:54:30.970/V: 
------------
[/storage/emulated/0/脚本/AntForest/ant-forest-launcher.js]运行结束，用时1.189000秒
```

**软件硬件信息**
操作系统: [ 安卓10 ]
设备型号: [Realme Q ]
Auto.js版本: [ 4.1.1 Alpha2 ]
项目版本: [ v2.0.4 ]

**Comment by qboyjim** [comment]
相同问题，报错代码也相同。安卓8，设备荣耀7，Auto.js版本4.1.1 Alpha2，项目版本: v2.0.4

**Comment by qboyjim** [comment]
把自动解锁中提示层面页面设置重新按照确实值更新后，问题解决

**Comment by CleverPuppy** [comment]
> 把自动解锁中提示层面页面设置重新按照确实值更新后，问题解决

估计是没有默认值，必须要通过设置脚本来设置一下不然就会报错

**Comment by JasonLeeTing** [comment]
> 把自动解锁中提示层面页面设置重新按照确实值更新后，问题解决

请问如何按照自己的机型重新更新确实值，小米10u，安卓11，Auto.js版本4.1.1 Alpha2，项目版本: v2.0.5

**Comment by CleverPuppy** [comment]
> > 把自动解锁中提示层面页面设置重新按照确实值更新后，问题解决
> 
> 请问如何按照自己的机型重新更新确实值，小米10u，安卓11，Auto.js版本4.1.1 Alpha2，项目版本: v2.0.5

v2.0.5已经解决这个问题了吧？看看log呢。我是用默认参数就行。如果不是这个问题就close了

**Comment by JasonLeeTing** [comment]
> > > 把自动解锁中提示层面页面设置重新按照确实值更新后，问题解决
> > 
> > 
> > 请问如何按照自己的机型重新更新确实值，小米10u，安卓11，Auto.js版本4.1.1 Alpha2，项目版本: v2.0.5
> 
> v2.0.5已经解决这个问题了吧？看看log呢。我是用默认参数就行。如果不是这个问题就close了

![1615908605770](https://user-images.githubusercontent.com/80761609/111336157-f0a9f100-86af-11eb-887e-3a8a7c4c2f0a.jpg)
任务定时启动后，会唤醒屏幕，但是不会到图形解锁界面

**Comment by CleverPuppy** [comment]
> > > > 把自动解锁中提示层面页面设置重新按照确实值更新后，问题解决
> > > 
> > > 
> > > 请问如何按照自己的机型重新更新确实值，小米10u，安卓11，Auto.js版本4.1.1 Alpha2，项目版本: v2.0.5
> > 
> > 
> > v2.0.5已经解决这个问题了吧？看看log呢。我是用默认参数就行。如果不是这个问题就close了
> 
> ![1615908605770](https://user-images.githubusercontent.com/80761609/111336157-f0a9f100-86af-11eb-887e-3a8a7c4c2f0a.jpg)
> 任务定时启动后，会唤醒屏幕，但是不会到图形解锁界面

好像不是同一个问题，建议开新issue

**Comment by CleverPuppy** [comment]
v2.0.5已修复
