### ISSUE TITLE
能量雨报错

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Ant-Forest#471]
执行能量雨任务，日志报错如下：小米10

00:49:18.474/E: Error: img is required for imagesx._buildRegion() (file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js#114)
Error: img is required for imagesx._buildRegion()
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js:114:0
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js:1213:0
    at collect (/storage/emulated/0/脚本/Ant-Forest-003/tools/energy-rain-harvesting.js:111:0)
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-global.js:187:0
    at /storage/emulated/0/脚本/Ant-Forest-003/tools/energy-rain-harvesting.js:28:0
    at /storage/emulated/0/脚本/Ant-Forest-003/tools/energy-rain-harvesting.js:10:0

**Comment by xy3217991** [comment]
此Bug未复现
