### ISSUE TITLE
能量雨报错

### ISSUE THREAD

**Issue by xy3217991** [SuperMonster003/Ant-Forest#537]
小米10运行能量雨报错，错误代码如下

11:33:59.878/E: Wrapped CvException [org.opencv.core.CvException: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
] (file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js#1486)
Wrapped CvException [org.opencv.core.CvException: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/core/src/matrix.cpp:367: error: (-215:Assertion failed) u != 0 in function 'void cv::Mat::create(int, const int*, int)'
]
    at _findColorInner (file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js:1486:0)
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js:1452:0
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/ext-images.js:1511:0
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/plugin-ant-forest-energy-rain.js:70:0
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/plugin-ant-forest-energy-rain.js:226:0
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/plugin-ant-forest-energy-rain.js:334:0
    at file:/storage/emulated/0/脚本/Ant-Forest-003/modules/plugin-ant-forest-energy-rain.js:348:0
    at /storage/emulated/0/脚本/Ant-Forest-003/tools/energy-rain-harvesting.js:1:0

**Comment by SuperMonster003** [comment]
内存不足 无法分配内存
尝试重启 Auto.js 后再次运行
可借助辅助工具 `./tools/auto.js-memory-info-tool.js`
