### ISSUE TITLE
Bug反馈: MIX4升级MIUI13后运行脚本直接崩溃

### ISSUE THREAD

**Issue by Z-L-X** [SuperMonster003/Ant-Forest#553]
**问题描述**
MIX4升级miui13后运行脚本auto.js崩溃

**日志截图**
崩溃信息如下：
Version: 461
Android: 31
android.os.RemoteException: Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs/com.stardust.autojs.core.image.capture.ScreenCaptureRequestActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5409)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

**软件硬件信息**
操作系统: miui13.0.2  基于安卓12
设备型号: MIX4
Auto.js版本: 4.1.1 Alpha2 
项目版本: v2.2.2

**其他**
换手机后每次运行脚本均会触发隐私提醒，导致脚本部分功能运行异常，如通过逛一逛按钮收取能量
![Uploading Screenshot_2022-02-11-21-01-32-281_org.autojs.autojs.jpg…]()

**Comment by SuperMonster003** [comment]
将在下一版本尝试修复上述问题 但开发周期可能较长 请关注后续版本更新

**Comment by Z-L-X** [comment]
辛苦大佬🥰

**Comment by TonyJiangWJ** [comment]
MIUI13 可以暂时用这个版本的AutoJS [修改版](https://github.com/TonyJiangWJ/Auto.js/releases/tag/v4.1.1)

**Comment by SuperMonster003** [comment]
感谢 Tony (◠‿◕)

**Comment by GodManRui** [comment]
MIUI13自己的bug，升级miui13更新补丁自己就好了

**Comment by SuperMonster003** [comment]
应该是屏幕截图时导致的崩溃
尝试使用 AutoJs6 后如果问题复现 可继续反馈

隐私提醒具体是什么
是需要授予额外的权限还是某些操作被视为敏感操作

**Comment by cyanhill** [comment]
@Z-L-X 获取手机信息需要修改成始终允许，我这边miui13给空白通行证会导致你这种崩溃
