### ISSUE TITLE
分析能量球的时候报错

### ISSUE THREAD

**Issue by czanan** [SuperMonster003/Ant-Forest#554]
Wrapped java.lang.Exception: unknown exception
    at file:///android_asset/modules/__images__.js:275:0
    at _getBalls (file:/storage/emulated/0/脚本/Ant-Forest-master-211103/modules/ext-images.js:1312:0)
    at _parse (file:/storage/emulated/0/脚本/Ant-Forest-master-211103/modules/ext-images.js:985:0)
    at _analyseEnergyBalls (file:/storage/emulated/0/脚本/Ant-Forest-master-211103/modules/ext-images.js:938:0)
    at file:/storage/emulated/0/脚本/Ant-Forest-master-211103/modules/ext-images.js:776:0

**Comment by czanan** [comment]
原来是autox的缘故，具体怎么修改还不知道

**Comment by SuperMonster003** [comment]
使用 AutoJs6 运行项目后 如果问题复现 可继续反馈
