### ISSUE TITLE
Bug反馈: auto.js崩溃

### ISSUE THREAD

**Issue by hebaodawang** [SuperMonster003/Ant-Forest#577]
**问题描述**
在开始任务后会正常跳转到支付宝蚂蚁森林页面，然后手机系统弹窗 映射什么的 自动跳过后 aotu.js就崩溃了 又要重新开启无障碍服务。无法运行这个问题在我手机系统更新到miui13后就出现了直到现在才下定决心反馈。

**日志截图**
Version: 461
Android: 31
android.os.RemoteException: Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs/com.stardust.autojs.core.image.capture.ScreenCaptureRequestActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5459)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

**软件硬件信息**
操作系统: [ 如: miui13 ]
设备型号: [ 如: 红米 k30 5g ]
Auto.js版本: [ 如: 4.1.1 Alpha2 ]
项目版本: [ 如: v2.2.2 ]

**其他**
[ 包括但不限于 建议/提案/想法/灵感... ]

**Comment by hebaodawang** [comment]
刚才尝试使用autojs6 配合2.3.0使用  开始运行好几次都是在自己蚂蚁森林页面不动，然后回来看了一下之前他们的反馈 发现是miui13后 应用权限的问题 刚才把权限给足了 现在可以正常使用了 目前autojs6+2.3.0 红米k30 5g miui13
